# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pr:
  - master

stages: 
 - stage: 
   jobs: 
    - deployment: firstJob
      pool:
        name: mypool
      environment: 
        name: 'SUPLAB_DEVOPS'
        resourceName: 'suplab-394-builder'
    - job:
      steps:
        - script: 
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml


  
